on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - macOS
        - ubuntu-latest
  push:
    branches:
    - main

jobs:
  benchmark:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Run benchmark
      run: |
        cd cppsandbox
        bazel run -c opt //example:benchmark

  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd cppsandbox
        bazel build //...

  test:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd cppsandbox
        bazel test //...